import { chromium } from 'playwright';
const b=await chromium.launch();
const p=await(await b.newContext({viewport:{width:1280,height:900}})).newPage();
const errs=[]; p.on('console',m=>m.type()==='error'&&errs.push(m.text())); p.on('pageerror',e=>errs.push('PE:'+e.message));
await p.goto('http://localhost:4000/',{waitUntil:'networkidle'});
const atTop=await p.evaluate(()=>{const b=document.getElementById('back-to-top');return {present:!!b,visible:b?b.classList.contains('is-visible'):null,aria:b?b.getAttribute('aria-label'):null};});
await p.evaluate(()=>window.scrollTo(0,2000)); await p.waitForTimeout(300);
const afterScroll=await p.evaluate(()=>document.getElementById('back-to-top').classList.contains('is-visible'));
await p.click('#back-to-top'); await p.waitForTimeout(800);
const afterClick=await p.evaluate(()=>window.pageYOffset||document.documentElement.scrollTop);
console.log(JSON.stringify({atTop, visibleAfterScroll:afterScroll, scrollYAfterClick:Math.round(afterClick), consoleErrors:errs}));
await p.screenshot({path:'tests/screenshots/r5-btt.png'});
await b.close();
